version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
    - "8080:8080"
volumes:
  data:
